# Generated by Django 5.1.2 on 2024-10-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=150)),
                ('motor_car', models.CharField(max_length=200)),
                ('firma_car', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
