# Generated by Django 5.1.2 on 2024-10-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=150)),
                ('motor_car', models.CharField(max_length=200)),
                ('firma_car', models.CharField(max_length=200)),
                ('image_car', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
